// SPDX-License-Identifier: MIT
pragma solidity >= 0.8.0;

import {DeployerHelper} from '../DeployerHelper.sol';

library UERC20MetadataDeployer {
    function deploy() internal returns (address uerc20Metadata) {
        bytes memory initcode_ = abi.encodePacked(initcode());
        uerc20Metadata = DeployerHelper.create2(initcode_);
    }

    /**
     * @dev autogenerated - run `./script/util/create_briefcase.sh` to generate current initcode
     *
     * @notice This initcode is generated from the following contract:
     * - Source Contract: src/pkgs/uerc20-factory/src/libraries/UERC20Metadata.sol
     */
    function initcode() internal pure returns (bytes memory) {
        return hex'';
    }
}
