name: Deploy to Tenderly Virtual TestNet
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - src/briefcase/deployers/**

jobs:
  deploy-to-tenderly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Create Tenderly Virtual TestNet environment: https://docs.tenderly.co/virtual-testnets
      - name: Setup Tenderly Virtual TestNet
        uses: Tenderly/vnet-github-action@v1.0.10
        with:
          access_key: ${{ secrets.TENDERLY_ACCESS_KEY }}
          project_name: ${{ vars.TENDERLY_PROJECT_SLUG }}
          account_name: ${{ vars.TENDERLY_ACCOUNT_SLUG }}
          testnet_name: "Uniswap VNet CI/CD ${{ github.run_id }}"
          mode: "CD"
          # ETH Mainnet config: https://docs.tenderly.co/supported-networks
          network_id: 1
          chain_id: 129412
          block_number: "latest"
          # Enable explorer & verification: https://docs.tenderly.co/virtual-testnets/testnet-explorer
          public_explorer: true
          verification_visibility: "src"
          state_sync: false

      # Fund wallet using unlimited faucet: https://docs.tenderly.co/virtual-testnets/unlimited-faucet
      - name: Fund Account
        env:
          TENDERLY_ADMIN_RPC_URL: ${{ env.TENDERLY_ADMIN_RPC_URL }}
          ADMIN_WALLET: ${{ vars.TENDERLY_ADMIN_WALLET }}
        run: |
          curl $TENDERLY_ADMIN_RPC_URL \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "jsonrpc": "2.0",
              "method": "tenderly_setBalance",
              "params": [
                "${{ vars.TENDERLY_ADMIN_WALLET }}",
                "0x3635c9adc5dea00000"
              ],
              "id": "1234"
            }'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Foundry Build
        run: |
          forge --version
          forge build --sizes

      # Deploy & verify contracts
      - name: Deploy Contracts
        env:
          PRIVATE_KEY: ${{ secrets.TENDERLY_PRIVATE_KEY }}
          FOUNDRY_ETH_RPC_URL: ${{ env.TENDERLY_PUBLIC_RPC_URL }}
          FOUNDRY_VERIFIER_URL: ${{ env.TENDERLY_FOUNDRY_VERIFICATION_URL }}
        run: |
          forge script script/deploy/Deploy-all.s.sol \
            --private-key $PRIVATE_KEY \
            --rpc-url $FOUNDRY_ETH_RPC_URL \
            --verify \
            --verifier custom \
            --verifier-url $FOUNDRY_VERIFIER_URL \
            --slow \
            --broadcast

      # Generate deployment logs
      # - name: Generate Deployment Logs
      #   env:
      #     TENDERLY_EXPLORER_URL: ${{ env.TENDERLY_EXPLORER_URL }}
      #   run: |
      #     rm deployments/129412.md && rm deployments/json/129412.json &&
      #     node lib/forge-chronicles Deploy-all.s.sol -c 129412 --force -e $TENDERLY_EXPLORER_URL

      # # https://github.com/marketplace/actions/tenderly-virtual-testnet-setup#outputs
      # - name: Add RPC URL to deployment logs
      #   env:
      #     TENDERLY_URL: ${{ env.TENDERLY_URL }}
      #   run: |
