name: test

on:
  pull_request:
    branches: [main, master, staging, dev, feat/**, fix/**]
  push:
    branches: [main, master, staging, dev]

env:
  FOUNDRY_PROFILE: ${{ github.event_name == 'push' && 'ci' || 'pr' }}

jobs:
  forge-test:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          echo Foundry profile: $FOUNDRY_PROFILE
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: forge test --isolate -vvv
        id: test
        env:
          FORGE_SNAPSHOT_CHECK: true
